workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest  # Ensures Codemagic uses the latest Xcode with iOS 15.5 support
      cocoapods: default
    scripts:
      # Install dependencies
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          cd ios && pod install
      
      # Build the iOS app
      - name: Build iOS App
        script: flutter build ios --release --no-codesign

    artifacts:
      - ios/build/**/*.ipa
